// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoPFSGWKI5ckWpi_Mdg1lPPmoL8i2xuS0',
    appId: '1:225964896624:web:5f02aa68bef8232c301fb5',
    messagingSenderId: '225964896624',
    projectId: 'chat-app-13adf',
    authDomain: 'chat-app-13adf.firebaseapp.com',
    storageBucket: 'chat-app-13adf.firebasestorage.app',
    measurementId: 'G-48EKSBRMMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ozMk1PlcdH_VGBvOTl9dvxbYgCenQoY',
    appId: '1:225964896624:android:4333a34b0b673319301fb5',
    messagingSenderId: '225964896624',
    projectId: 'chat-app-13adf',
    storageBucket: 'chat-app-13adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0ciQdzHqxTiNbK2cJTYvoaBZHcSQjGc',
    appId: '1:225964896624:ios:adddec86f12c6d69301fb5',
    messagingSenderId: '225964896624',
    projectId: 'chat-app-13adf',
    storageBucket: 'chat-app-13adf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0ciQdzHqxTiNbK2cJTYvoaBZHcSQjGc',
    appId: '1:225964896624:ios:adddec86f12c6d69301fb5',
    messagingSenderId: '225964896624',
    projectId: 'chat-app-13adf',
    storageBucket: 'chat-app-13adf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoPFSGWKI5ckWpi_Mdg1lPPmoL8i2xuS0',
    appId: '1:225964896624:web:31fa7389eafe299b301fb5',
    messagingSenderId: '225964896624',
    projectId: 'chat-app-13adf',
    authDomain: 'chat-app-13adf.firebaseapp.com',
    storageBucket: 'chat-app-13adf.firebasestorage.app',
    measurementId: 'G-2X8SD870BG',
  );
}
